---
name: 'Docker Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
    value: ${{ steps.docker.outputs.output }}

runs:
  using: composite
  steps:
    - id: docker
      uses: 'docker://alpine:3.8'
      with:
        entrypoint: "sh -l -c -- "
        args: |
          OUTPUT="$(echo "${{ toJSON(inputs) }}" | jq '.[]')"
          printf -- "Command output:\n${OUTPUT}"
          echo "::set-output name=output::${OUTPUT}

    - run: echo "::notice title=Output::${{ steps.docker.outputs.output }}"
      shell: bash

