---
name: 'Docker Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
    value: ${{ steps.docker.outputs.output }}

runs:
  using: composite
  steps:
    - id: docker
      uses: 'docker://alpine:latest'
      with:
    #     pre-entrypoint: "entrypoint.sh"
        entrypoint: "sh"
        args: -lc --
          'echo "::set-output name=output::${{ inputs.who-to-greet }}X"'
      name: "1"
    - run: echo "::set-output name=output::$(
        docker run --entrypoint sh alpine -lc --
          'echo ${{ inputs.who-to-greet }}'
        )"
      shell: bash
      id: d
      name: "2"

    # - run: |
    #     docker containter run
    #   shell: bash
    - run: echo "::notice title=Output::${{ steps.docker.outputs.output }}"
      shell: bash
    - run: echo "::notice title=Output2::${{ steps.d.outputs.output }}"
      shell: bash

