---
name: 'Docker Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
    value: ${{ steps.docker.outputs.output }}

runs:
  using: composite
  steps:
    - id: docker
      uses: 'docker://alpine:latest'
      with:
    #     pre-entrypoint: "entrypoint.sh"
        entrypoint: "sh"
        args: |
          -lc -- echo "::set-output name=output::${{ toJSON(inputs) }}"

    # - run: |
    #     docker containter run
    #   shell: bash
    - run: echo "::notice title=Output::${{ steps.docker.outputs.output }}"
      shell: bash

